### Site Settings ###
title: "Hicham El Mehdi"
description: >
  Ingénieur en Intelligence Artificielle | Computer Vision & Deep Learning
  Passionné par l'innovation technologique et les systèmes intelligents
baseurl: "/Portfolio"                    # Nom de ton dépôt GitHub Pages
url: "https://mehdihch.github.io/Portfolio"        # Ton URL GitHub Pages
repository: "MehdiHCH/Portfolio"         # Nom complet du dépôt
destination: docs                       # Optionnel : définit docs comme dossier de sortie

remote_theme: yousinix/portfolYOU        # Thème officiel portfolYOU
open_new_tab: false                      # Liens externes dans un nouvel onglet

### Plugins ###
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-github-metadata

### Sass ###
sass:
  sass_dir: ../_sass
  style: compressed

### Navbar Settings ###
nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Author Info ###
author:
  name: "EL MEHDI Hicham"
  image: "/Portfolio/assets/img/profil/Me.jpeg"     
  email: "mehdihicham736@gmail.com"
  github: "MehdiHCH"
  linkedin: "elmehdihicham"

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Defaults ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false

### Analytics ###
analytics:
  enabled: false
  google:
    tracking_id: ""

### Buy Me a Coffee ###
buymeacoffee:
  enabled: false
  username: ""
  color: "#007bff"
  message: "Merci pour votre visite !"

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"